### ISSUE TITLE
Getting This Error Bot not Working

### ISSUE THREAD

**Issue by bowler14** [sizifart/RockyRabbitBot#1]
2024-09-12 17:26:03 | ERROR    | 896 - Hero | Unknown error: list index out of range
Traceback (most recent call last):
  File "/home/hero/Desktop/TG_Bot/New_Bot/RockyRabbitBot/bot/core/tapper.py", line 686, in run
    tg_web_data = await self.get_tg_web_data(proxy)
  File "/home/hero/Desktop/TG_Bot/New_Bot/RockyRabbitBot/bot/core/tapper.py", line 137, in get_tg_web_data
    start_param = settings.REF_LINK.split("=")[1]
IndexError: list index out of range

**Comment by bowler14** [comment]
> 2024-09-12 17:26:03 | ERROR | 896 - Hero | Unknown error: list index out of range Traceback (most recent call last): File "/home/hero/Desktop/TG_Bot/New_Bot/RockyRabbitBot/bot/core/tapper.py", line 686, in run tg_web_data = await self.get_tg_web_data(proxy) File "/home/hero/Desktop/TG_Bot/New_Bot/RockyRabbitBot/bot/core/tapper.py", line 137, in get_tg_web_data start_param = settings.REF_LINK.split("=")[1] IndexError: list index out of range

**i got it i have to give full link but after doing that previous error is gone but new error arries getting html code ** 

**2024-09-12 17:32:14 | INFO     | 130 - hero | login failed... Response code: 403
2024-09-12 17:32:14 | INFO     | 889 - Sleep 291 seconds...**
<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />

<style>body{margin:0;padding:0}</style>



<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
much more code .......
